sudo: required
services:
  - docker

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install curl
  - docker-compose up -d

script:
  - docker ps
  - ./test.sh

after_script:
  - docker-compose down

notifications:
  email: docker@katagena.com
